export const chatDummy = [
  {
    id: '1',
    roomId: '1234',
    name: '디카프리오',
    message: '안녕하세요.adajfaldsjfalsjfadajfaldsjfalsjfadajfaldsjfalsjfadajfaldsjfalsjfadajfaldsjfalsjfadajfaldsjfalsjfadajfaldsjfalsjf',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
  {
    id: '2',
    roomId: '1234',
    name: '김성욱',
    message: '안녕하세요.',
    createdAt: new Date(),
    createdBy: '9',
    isTransferred: true,
  },
  {
    id: '3',
    roomId: '1234',
    name: '디카프리오',
    message: '날씨가 좋네요.',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
  {
    id: '4',
    roomId: '1234',
    name: '김성욱',
    message: '점심 잘 드렸나요?',
    createdAt: new Date(),
    createdBy: '9',
    isTransferred: true,
  },
  {
    id: '5',
    roomId: '1234',
    name: '도배꾼',
    message: '사라져라',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
  {
    id: '6',
    roomId: '1234',
    name: '도배꾼',
    message: '사라져라',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
  {
    id: '7',
    roomId: '1234',
    name: '도배꾼',
    message: '사라져라',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
  {
    id: '8',
    roomId: '1234',
    name: '도배꾼',
    message: '사라져라',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
  {
    id: '9',
    roomId: '1234',
    name: '도배꾼',
    message: '사라져라',
    createdAt: new Date(),
    createdBy: '1234',
    isTransferred: true,
  },
];
